In [1]:
import numpy as np

In [2]:
x = np.array([1.0, 2.0, 3.0])

In [3]:
print(x)

[1. 2. 3.]


In [4]:
type(x)

numpy.ndarray

In [5]:
y = np.array([2.0, 4.0, 6.0])

In [6]:
x + y

array([3., 6., 9.])

In [7]:
y

array([2., 4., 6.])

In [8]:
A= np.array([[1,2],[3,4]] )

In [9]:
A.shape

(2, 2)

In [10]:
A.dtype

dtype('int64')

In [11]:
B = np.array([[3,0],[0,6]])

In [12]:
A + B

array([[ 4,  2],
       [ 3, 10]])

In [13]:
A * B

array([[ 3,  0],
       [ 0, 24]])

넘파이에서는 서로 다른 형상의 배열끼리도 계산할 수 있습니다

In [16]:
A = np.array( [[1,2],[3,4]] )
B = np.array( [[10,20]] )

In [17]:
A+B

array([[11, 22],
       [13, 24]])

In [18]:
A*B

array([[10, 40],
       [30, 80]])

지금 까지의 방법 외에도 인덱스를 배열로 지정해 한 번에 여러 원소에 접근 가능하기도 합니다. 

In [19]:
X = np.array( [ [51,55],[14,19],[0,4]])

In [20]:
X = X.flatten() #X 를 1차원 배열로 변환 = 평탄화 합니다 

In [21]:
print(X)

[51 55 14 19  0  4]


In [24]:
X[np.array([0,2,4])] # 0,2,4번 원소 얻기 

array([51, 14,  0])

In [25]:
X


array([51, 55, 14, 19,  0,  4])

In [26]:
X > 15

array([ True,  True, False,  True, False, False])

In [27]:
X[X>15] #해당 조건을 만족하는 애들만 얻어질거임 

array([51, 55, 19])

단순한 그래프 그리기 , pyplot 모듈을 이용합니다 