In [1]:
import numpy as np


In [5]:
A = np.array([[56.0 , 0.0 , 4.4, 68.0],[1.2, 104.0, 52.0,8.0],[1.8, 135.0 ,99.9, 0.9]])

In [6]:
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.9   0.9]]


In [10]:
cal = A.sum(axis=0)
print(cal)
print(cal.reshape(1,4))

[ 59.  239.  156.3  76.9]
[[ 59.  239.  156.3  76.9]]


In [13]:
print(A)
print()
print(cal.reshape(1,4))
print()
print(A/cal.reshape(1,4))



[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.9   0.9]]

[[ 59.  239.  156.3  76.9]]

[[0.94915254 0.         0.02815099 0.88426528]
 [0.02033898 0.43514644 0.33269354 0.10403121]
 [0.03050847 0.56485356 0.63915547 0.01170351]]


In [9]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.81509917 88.42652796]
 [ 2.03389831 43.51464435 33.26935381 10.40312094]
 [ 3.05084746 56.48535565 63.91554702  1.17035111]]
