In [1]:
import numpy as np

a = np.random.randn(5)  #this creates a data structure (5,) called Rank 1 Array 
                        #and it does not behave consistently as either a row vector nor a column vector 

In [2]:
print(a)

[ 1.42871045 -0.43133021  0.09153415  0.32059054  0.99796413]


In [3]:
print(a.shape)
#this one is called rank 1 array in Python 

(5,)


In [4]:
print(a.T)

[ 1.42871045 -0.43133021  0.09153415  0.32059054  0.99796413]


In [5]:
print(np.dot(a,a.T))  
#strange huh ? 

3.3343485082892625


In [6]:
a= np.random.rand(5,1)
print(a)

[[0.38036834]
 [0.60658247]
 [0.18876522]
 [0.65641477]
 [0.03469646]]


In [7]:
print(np.dot(a,a.T))

[[0.14468008 0.23072477 0.07180031 0.2496794  0.01319744]
 [0.23072477 0.36794229 0.11450167 0.39816969 0.02104626]
 [0.07180031 0.11450167 0.03563231 0.12390828 0.00654949]
 [0.2496794  0.39816969 0.12390828 0.43088034 0.02277527]
 [0.01319744 0.02104626 0.00654949 0.02277527 0.00120384]]


In [ ]:
#now we got matrix result 