In [2]:
import numpy as np

In [2]:
A = np.array([1,2,3,4])
print(A)


[1 2 3 4]


In [3]:
np.ndim(A)

1

In [4]:
np.shape(A)

(4,)

In [5]:
A.shape[0]

4

### 2-d array ?

In [8]:
B = np.array([[1,2],[3,4],[5,6]])

In [9]:
print(B)

[[1 2]
 [3 4]
 [5 6]]


In [10]:
np.ndim(B)

2

In [11]:
B.shape[0]

3

In [12]:
B.shape

(3, 2)

### 신경망에서의 행렬곱. 

In [3]:
X = np.array([1,2])
X.shape

(2,)

In [4]:
W = np.array([[1,3,5],[2,4,6]])

In [5]:
print(W)

[[1 3 5]
 [2 4 6]]


In [6]:
W.shape

(2, 3)

In [7]:
Y = np.dot(X,W)

In [8]:
print(Y)

[ 5 11 17]


## 그러면 직접 구현해봅시다

In [10]:
X = np.array([1.0, 0.5])
W1 = np.array([ [0.1, 0.3, 0.5],[0.2, 0.4, 0.6] ])
B1 = np.array([0.1, 0.2, 0.3])

A1 = np.dot(X,W1) + B1 

In [11]:
print(A1)

[0.3 0.7 1.1]


In [12]:
def sigmoid(A):
    return 1 / (1 + np.exp(-A))

In [13]:
Z1 = sigmoid(A1)

In [14]:
print(Z1)

[0.57444252 0.66818777 0.75026011]


In [15]:
W2 = np.array( [[0.1,0.4],[0.2,0.5], [0.3,0.6]] )
B2 = np.array( [0.1 , 0.2])


In [16]:
print(Z1.shape)
print(W2.shape)
print(B2.shape)

(3,)
(3, 2)
(2,)


In [19]:
A2 = np.dot(Z1, W2) #Z1 아웃풋을 인풋으로..
Z2 = sigmoid(A2) + B2

In [20]:
print(Z2)

[0.70256397 0.93380749]


In [21]:
W3 = np.array( [[0.1,0.3], [0.2,0.4]])
B3 = np.array([0.1, 0.2])
A3 = np.dot(Z2, W3) + B3

In [22]:
Y = A3
print(Y)

[0.3570179  0.78429219]
